### ISSUE TITLE
단발성 이벤트 효과 측정에 대해 질문드립니다.

### ISSUE THREAD

**Issue by 1Chic** [ncsoft/promotionImpact#2]
기간을 정한 프로모션이 아닌, 특정 이벤트 발생시의 효과 측정은 이 패키지로는 구현하기가 힘들지요?

예를 들어, 4월 10일 **당일에만 특정 이벤트**가 있고, 해당 이벤트의 효과가 몇일간 지속된다고 가정합니다.
이 이벤트에 대한 효과 측정을 하려면, date 설정을 아래와 같이 해야하는데요. 
- start_date : 04/10
- end_date :  **효과가 끝났다고 생각되는 날짜**를 분석을 통해 직접 찾아야 한다.

end_date를 자동으로 찾거나, 쉽게 찾을 수 있는 방법이 package내에서는 제공되지 않는지 궁금합니다.

좋은 package만들어주셔서 감사합니다.

**Comment by danbi-ncsoft** [comment]
안녕하세요.
현재 패키지에서는 특정 이벤트의 종료 시점을 자동으로 찾는 기능은 구현되어 있지 않습니다. 다만, 내부적으로는 어떤 프로모션이 끝난 이후에 남아있는 효과를 추정하기 위한 기능을 구현하기 위한 계획을 갖고 있습니다. 아마 질문 주신 내용은 이것과 관련이 있을 것 같습니다.
차후 패키지 업데이트 시 질문 주신 내용도 적극 고려하겠습니다.
혹시 그 외에 패키지 사용하시면서 다른 아이디어 있으시면 언제든 의견 주세요. 
감사합니다.
