### ISSUE TITLE
효과 측정 기준에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by hyo02083** [ncsoft/promotionImpact#3]
안녕하세요, 먼저 좋은 라이브러리 감사합니다.
패키지 사용 도중 궁금한 사항이 생겨 질문드립니다.

 해당 이벤트 효과가 얼마나 잘 측정이 되었는가에 대한 기준이 따로 있을까요?
예를 들면, RMSE값인지 또는 R^2 값인지 또, 해당 값들이 어떤 수치를 가질 때 잘 측정되었다고 할 수 있는지 기준에 대해서 알고 싶습니다. 

또 coefficient가 높은 이벤트 변수라 할지라도 p-value가 높을 때(유의 하지 않을 때) 해당 변수를 어떤식으로 처리하게 되는지도 알고 싶습니다.

**Comment by danbi-ncsoft** [comment]
효과 추정치의 신뢰도를 측정하는 문제는 저희도 아직 많이 고민하고 있는 주제입니다. 기본적으로 promotionImpact 의 목적은 값의 예측이 아니라 효과를 추정하는 것이기 때문에 RMSE 를 낮추는 것이 반드시 좋은 것은 아닙니다. 대신 모델의 잔차가 최대한 white noise 에 가까운지를 확인하는 것이 더 적절하다고 생각합니다.
그래서 최근에 추가한 compareModel 함수의 경우 잔차의 주기성과 정규성을 확인하여 최적의 옵션을 추천해주도록 구현하였습니다. 다만, 이건 직접적으로 개별 이벤트 효과 추정치의 정확도를 나타내는 것은 아니기 때문에 질문에 대한 직접적인 답은 아닌 것 같네요.

한편, 어떤 이벤트 변수의 회귀 계수에 대한 p-value가 높다고 해서 패키지 자체에서 자동으로 그 변수를 제거하지는 않습니다. 사용자가 모델의 결과를 보고 (결과를 활용할지 말지를) 직접 판단해야 합니다. 가장 좋은 건 추정치와 함께 +- 신뢰 구간 값을 같이 활용하는 것입니다. 
또한 제 생각에, 회귀 계수의 p-value 가 의미하는 것은 '회귀 계수가 0이다.' 라는 영가설 상황에서 측정된 통계량 이상의 극단값을 관측할 확률이기 때문에 반대의 경우(low coefficient & p-value)는 종종 있지만, 질문하신 것처럼 coefficient가 매우 높으면서 p-value도 높은 경우는 (데이터가 부족한 경우가 아니라면) 발생하기 힘들 것 같습니다. 

감사합니다.
