### ISSUE TITLE
end_date 설정 관련 질문

### ISSUE THREAD

**Issue by akclau** [ncsoft/promotionImpact#4]
1.  end_date를 설정할 때 정확히 프로모션이 시행된 기간으로 설정해야하나요? 아니면, 해당 이벤트의 효과가 몇일 지속 된다고 가정하여 몇일을 + 하여 설정해야 하는지 궁금합니다. 

2. start_date와 end_date의 차이가 작을 경우(단발성 이벤트), "Local regression result(smoothed value) included NaN or -Inf value. Need to specify a bigger bandwidth parameter or reduce the number of smooth.except.date." 에러 메시지가 발생합니다.  혹시 해결 방법이 있을까요? 

3. 회귀 모델이 만들어지면, predict 하는 기능이 있는지 궁금합니다.

5. effect 가 음수(-)가 나올경우, 어떻게 해석해야 하는지 궁금합니다. 

감사합니다.

**Comment by danbi-ncsoft** [comment]
1. 입력된 이벤트 기간 동안 발생한 프로모션 매출액을 바탕으로 해당 프로모션의 효과를 추정하는 것이기 때문에 end_date는 프로모션이 시행된 기간으로 설정하는 것이 의도에 맞습니다. 
2. 1차적으로는 promotionImpact 함수 옵션에서 smooth.bandwidth를 바꾸어서 시도해 보는 것을 추천드립니다. 그래도 해결되지 않는다면 너무 단발성 이벤트라 양상을 추정할만큼 데이터가 충분하지 않아서 발생하는 문제로 추정됩니다.
3. 어떤 것을 예측하고자 하시는지는 모르겠으나, promotionImpact는 이미 발생한 매출액을 바탕으로 프로모션의 효과를 추정하는 것이기 때문에 함수 내부에 직접적으로 예측 기능이 있지는 않습니다. 
다만, promotionImpact의 output중 추정된 회귀 모델은 pri1$model$model의 형태로, 
이에 사용된 data는 pri1$model$final_input_data의 형태로 존재하므로 필요한 경우 활용은 가능합니다.
4. 정확히 프로모션이 전체 매출에 마이너스 영향력을 가져다주었다고 해석하기에는 조심스럽습니다만, 모델에 삽입하신 여러 요소들을 고려하고 나니 해당 기간의 전체 매출 변동분 중 해당 프로모션의 시행이 평균적으로 감소에 기여했다고 볼 수 있을 것 같습니다.
일반적으로는 프로모션을 진행하면 기타 요소(전체 매출이 증가하고 있는 트렌드 등)를 감안할 지라도 프로모션 상품의 판매액이 충분히 높아 효과가 양수로 도출되곤 합니다.
그러나 말씀하신 경우에는 해당 프로모션을 시행하지 않았더라면 평균적으로 전체 매출이 더 증가했을 것이다를 내포할 수 있습니다.

감사합니다.

**Comment by akclau** [comment]
1. 예제 데이터에서는 2년 반 정도 관찰 기간을 설정하였는데, 관찰 기간이 길 수록 유리한지 궁금합니다. 최소 관찰기간이 몇개월인지도 궁금합니다. 

2. 1차 사용 목적은 시간이 지날 수록 어떤 이벤트 효과가 좋아지는지 나빠지는지 알기 위해 주기적으로 갱신하여 사용하고 싶습니다. 그런데 예를들어 똑같은 매출을 기록한 장비 이벤트 일지라도, 관찰 기간에 따라서 effect가 크게 변화하는 것 같습니다. 

장비이벤트 :  05/01 ~ 05/15(15일 진행)
관찰기간 설정 : 03/01~ 06/01(3개월, effect =16)  ---> 03/07 ~06/07(3개월, effect=4) ---> 03/14  ~ 06/14(3개월, effect = -8) 

다음과 같이 주단위로 갱신하여 effect를 확인할 경우,  장비 이벤트로 인해 발생한 매출은 고정적인데 effect 수치 변동이 큽니다. 

이런식으로 갱신해서 확인하는 활용 접근 자체가 잘못된 것인지, 아니면 시간이 흐를수록, 전체 매출자체가 감소 추세에 있어서 효과가 낮아지는 건지 어떤건지 궁금합니다.

3. 관찰기간을 1개월 혹은 2개월 처럼 짧게 설정 할경우, 이벤트 effect가 NA값이 무조건 발생하는데, 무엇 때문에 NA가 발생하는지 좀더 자세하게 설명을 듣고 싶습니다.

4. effect 값 해석의 경우, 시계열 모델을 만들었을 때 기대되는 값Y_hat과 실제발생한 매출Y와의 차이를 효과로 보는 방식으로 이해하였는데 올바르게 해석한건가요? 이게 맞다면.. 여러 이벤트중 특정 이벤트는 1회 밖에 시행되지 않을 경우 어떻게 Y_hat이 만들어질 수 있나요? 

5. 추가로 이 패키지를 활용하여 적용할 수 있는 예시를 듣고 싶습니다. 이벤트 효과를 갱신하여 보아 효과가 떨어진 이벤트 원인 분석을 한다던지.. 단순히 효과를 확인하고 끝나는 것이 아니라 이를 실무에서 활용할 수 있는 구체적 방안 같은것들이 있는지 예시 정도를 알고 싶습니다.

감사합니다.

**Comment by akclau** [comment]
답변 달아주시면 감사하겠습니다. :)

**Comment by danbi-ncsoft** [comment]
1. 관찰 기간이 길다면 그만큼 쌓인 정보가 많겠지만, 너무 오래된 데이터를 사용하는 경우에는 여러 요소를 고려한다고 하더라도 현재와 동떨어진 값을 제공할 가능성도 배제하지 않을 수 없기 때문에 관찰기간이 길다고 해서 무조건 유리하다고 볼 수는 없습니다.
지난 1년 간의 매출 대비 프로모션의 매출 증대 효과와 지난 3년 간의 매출 대비 프로모션의 매출 증대 효과 중 어떤 것이 알고 싶은지의 차이임과 동시에 변수로 고려하기 어려운 사람들의 선호도 변화 등을 감수하면서까지 3년 전 매출과도 비교가 필요한가의 판단이 필요한 부분이 아닐까 싶습니다.
그리고 최소 관찰 기간은 정해져 있다기 보다는 프로모션 유형 종류 등 해당 데이터의 특성마다 다를 수 있을 것 같은데, 일반적으로는 promotionImpact의 lm객체에서 계수 값을 계산할 수 있는 정도면 되지 않을까 싶습니다.

2. 시간에 따른 이벤트의 효과를 확인하는 방법 자체는 의도에 맞게 잘 사용하고 계신 것 같습니다. 
분석하고자 하시는 데이터 고유의 특성을 알 수 없기 때문에 섣불리 말씀드리기는 어렵지만
먼저 말씀하신 것처럼 전체 매출 자체의 증감 추세로 인하여 해당 상황이 발생할 수도 있고, 
관찰 기간이 변화함에 따라 이벤트 효과 분석의 기준이 되는 매출도 함께 달라지게 되어 발생한 결과일 수도 있습니다. 따라서 매출 감소로 인한 영향이 의심되어 이를 제어하고 싶으신 경우, 
promotionImpact의 함수에 trend = TRUE 옵션을 활용해보셔도 좋을 것 같습니다.
그럼에도 불구하고 수치 변동이 크다고 느껴지신다면 trend 옵션이 고려한 전반적 트렌드 양상보다
갱신된 기간의 변화가 갑자기 커지는 등의 원인으로도 의심해볼 수 있을 것 같습니다.
그 외에도 언급하신 장비 이벤트 외에 다른 이벤트가 관찰 기간에 진행되었다면 그로 인한 요인 또한 완전히 배제하기는 어렵습니다.

3. 1번에서의 최소 관찰 기간에서 말씀드린 맥락과 비슷한 것 같습니다. 
1-2개월이라면 관측치의 개수가 30~60일 남짓 될 것이고 해당 기간의 데이터가 선형 회귀 모형의 모든 계수를 계산할 만큼 충분히 다양한 케이스를 가지고 있지 않은 경우 NA가 발생됩니다.
예를 들어 유형 A와 유형 B의 프로모션이 해당 기간에 단 하나밖에 진행되지 않았는데 그 기간이 완전히 겹쳐버린 경우라면 두 프로모션의 효과를 서로 쪼갤 만한 다른 정보가 하나도 없기 때문에 다중공선성이 발생하여 NA가 도출될 수 있습니다.
이때 모형에 사용된 데이터는 pri1$model$final_input_data에 data.frame으로 확인하실 수 있으므로
NA가 발생하는 유형의 변수와 다른 유형의 변수를 유심히 살펴보시면 NA의 발생 이유를 찾으실 수 있을 것 같습니다.

4. 제가 질문을 제대로 이해한 것이 맞다면, 그 차이는 분석 기간의 전체 이벤트들의 평균적인 효과 대비 해당 이벤트의 평균적 효과라고 올바르게 해석하고 계신 것 같습니다. 
그리고 1회 밖에 시행되지 않은 '이벤트'란 혹시 이벤트의 '유형'을 말씀하시는 것인가요?
만약 지금까지는 유형 A나 B 이벤트만 시행되었는데, 완전히 새로운 유형 C의 이벤트가 나온 경우 어떻게 만들어지는지를 물으신것이라면 , 이 경우 지금까지 시행되었던 모든 이벤트의 평균으로 계산되고 있습니다. 그러므로 해석을 하실 때에는 진행 되었던 전체 이벤트 대비 해당 이벤트의 영향이라고 보는 것이 좋을 것 같습니다.

5. 가장 간단하게 확장시켜보면, 전체 매출이 아닌 특정 고객들이 발생시킨 매출에 대해서만 분석을 하여 어떤 특징을 가진 고객들에게 특히 이 프로모션의 효과가 좋았는지 등을 살펴볼 수 있습니다.
고객들을 어떤 기준을 통해 몇 가지의 그룹으로 나눈 다음, 각 그룹의 고객들이 발생시킨 매출에 대한 영향력을 분석해보면 어떤 그룹에서는 효과가 좋았지만 반대로 어떤 그룹에서는 효과가 미미했던 이벤트가 충분히 있을 것이고, 먄약 그 이벤트가 특정 고객층을 겨냥헀던 이벤트였다면 타겟팅이 적절히 되었다고 판단할 수도 있을 것입니다.

감사합니다.

**Comment by akclau** [comment]
빠르게 답변해주셔서 감사합니다.
추가 질문이 생겨 
-

**Comment by akclau** [comment]
빠르게 답변해 주셔서 감사합니다:)
그런데 추가 질문이 생겨서 다시 글을 남기게 되었습니다.

1. 예제에서 sim.promotion.sales은 sim.promotion과 달리 payment 값을 활용하여 smoothing function을 추정 하는 것으로 알고 있는데요. 
payment 값이 제대로 적용되고 있지 않는 것 같습니다.

**ex1)**
> sim.promotion.sales2 <- sim.promotion.sales %>% **mutate(payment = ifelse(tag_info == "A", 300,
                                                                      ifelse(tag_info == "B", 800,
                                                                         ifelse(tag_info == "C", 900, 
                                                                            ifelse(tag_info == "D", 100,
                                                                               ifelse(tag_info == "E", 50, payment))))))**

>  pri22 <- promotionImpact(data=sim.data, promotion=sim.promotion.sales2, 
                           time.field = 'dt', target.field = 'simulated_sales',
                           dummy.field = 'month_start',
                           trend = T, period = 30.5, trend.param = 0.02, period.param = 2,
                           logged = T, differencing = T)
 
>  pri22$effects
         A        B        C        D        E
**1 34.16627 25.24344 15.43608 13.98401 4.604008**

**ex2)**
> sim.promotion.sales3 <- sim.promotion.sales %>% **mutate(payment = 2)**

> pri33 <- promotionImpact(data=sim.data, promotion=sim.promotion.sales3, 
                         time.field = 'dt', target.field = 'simulated_sales',
                         dummy.field = 'month_start', var.type = 'smooth',
                         trend = T, period = 30.5, trend.param = 0.02, period.param = 2,
                         logged = T, differencing = T)

>  pri33$effects
         A        B        C        D        E
1 **34.16627 25.24344 15.43608 13.98401 4.604008**

임의로 payment값을 바꾸어보았는데, ex1과 ex2의 결과가 똑같이 나오는 거 같습니다. 
뭔가 파라미터값을 추가해줘야 작동 하는건지 궁금합니다!








2. 패키지를 적용해 보면서 든 의문점이 있습니다. 
예를들어 장비 관련 이벤트를 했을 때, **장비 상품 자체**의 판매량은 다른 상품 대비 적은 편인데, effect가 높게 나오는 경우 정확한 해석이 궁금합니다. 

**해당 상품의 판매량**과 그 이벤트의 **effect**는 비례하지 않을 수 있다라는 것을 알고는 있지만, 

예를 들어 '장비 상품 자체의 판매량은 적었지만 장비 관련 이벤트를 시행함으로써, 그 이벤트 **기간**의 전체 매출 상승에 기여도가 높았다' 또는 반대로 'xx이벤트 자체의 판매량은 높았지만 전체 매출 상승 효과는 약했다' 라고 해석하는 것이 맞을지 .. 올바른 해석이 궁금합니다.


참고로 
예제데이터(sim.promoiton.sales)에서도 effect는 A>B>C>D>E 이지만, 상품별 매출량은 A>B>**D**>C>E 로 나타났습니다.

> pri2$effects
         A        B        C        D        E
1 23.17503 15.93217 12.36749 9.248766 4.570775

  tag_info     payment2
  <chr>           <dbl>
1 A        90379547483.
2 B        85834203305.
3 D        64301653947.
4 C        61338944922.
5 E        31353034865.

감사합니다.

**Comment by danbi-ncsoft** [comment]
1. 적어주신 코드를 실행시켜 보니, ex2는 질문주신 분과 동일한 결과가 나오는데, ex1은
```
A B C D E
1 35.60086 24.84473 17.68977 13.87022 5.736935
```
로 말씀하신 두 예시는 서로 결과가 다르게 잘 나옵니다 :)

2.  말씀하신 것처럼 평균적으로 장비 상품의 매출이 적었다고 해서 무조건 그 때 시행되었던 이벤트의 효과가 나빴다는 것은 아닙니다.
예를 들어 해당 상품이 판매되었던 시기가 연중 매출이 낮던 시기여서 그 영향으로 장비 상품의 매출이 다른 시기에 판매되었던 상품들에 비해 낮았을 수도 있고, 동시에 시행되었던 이벤트로 인하여 다른 상품들을 사느라 선호도가 덜한 상품의 판매는 부진했을 수도 있을 것입니다.
그렇기 때문에 추가로 통제해야할 사항들을 변수로 모두 고려했는데도 불구하고 매출은 그다지 높지 않았지만 효과가 좋게 나온 경우는 일반적으로 '해당 이벤트가 아니었으면 매출이 더 적게 나왔을 것인데, 해당 이벤트가 매출을 어느 정도 끌어올려 주었다'고 해석하시는게 어떨까 싶습니다.

감사합니다.

**Comment by akclau** [comment]
`pri3$effects
         A        B        C        D        E
1 34.16627 25.24344 15.43608 13.98401 4.604008
`

**Comment by akclau** [comment]
2번 내용 잘 이해했습니다. 감사합니다~ 
그런데..  **1번** 질문 관련하여
패키지를 지웠다가 다시 설치해도 
저는 계속 effect가 똑같은 결과만 나오는 것 같습니다...

rm(list=ls())
 library(dplyr)
 library(promotionImpact)
 
 sim.data <- sim.data %>%
    dplyr::mutate(month_start = ifelse(substr(as.character(dt),9,10) == '01', 1, 0))
 
 # 기본 예제
 pri <- promotionImpact(data = sim.data, promotion = sim.promotion.sales,
                        time.field = 'dt', target.field = 'simulated_sales',
                        dummy.field = 'month_start',trend.param = 0.02, period.param = 2,
                        trend = T, period = 30.5, logged = T, differencing = T)
 pri$effects
 
 
 # ex1
 sim.promotion.sales2 <- sim.promotion.sales %>% mutate(payment = ifelse(tag_info == "A", 10,
                                                                         ifelse(tag_info == "B", 1,
                                                                                ifelse(tag_info == "C", 0.3,
                                                                                       ifelse(tag_info == "D", 100000,
                                                                                              ifelse(tag_info == "E", 50000000, payment))))))

 pri2 <- promotionImpact(data = sim.data, promotion = sim.promotion.sales2,
                         time.field = 'dt', target.field = 'simulated_sales',
                         dummy.field = 'month_start', trend.param = 0.02, period.param = 2,
                         trend = T, period = 30.5, logged = T, differencing = T)
 pri2$effects
 
 
 # ex2
 sim.promotion.sales3 <- sim.promotion.sales %>% mutate(payment = 0.3)
 
 pri3 <- promotionImpact(data = sim.data, promotion = sim.promotion.sales3,
                        time.field = 'dt', target.field = 'simulated_sales', 
                        dummy.field = 'month_start',trend.param = 0.02, period.param = 2,
                        trend = T, period = 30.5, logged = T, differencing = T)
 pri3$effects


>  pri$effects
         A        B        C        D        E
1 23.17503 15.93217 12.36749 9.248766 4.570775

>  pri2$effects
         A        B        C        D        E
1 34.16627 25.24344 15.43608 13.98401 4.604008

>  pri3$effects
         A        B        C        D        E
1 34.16627 25.24344 15.43608 13.98401 4.604008

**Comment by danbi-ncsoft** [comment]
안녕하세요. 결론부터 말씀드리면 효과 값은 동일하게 나오는 것이 정상입니다.
(지난 답변에서 다르게 나온다고 말씀드렸는데, 제가 적어주신 코드를 실행시키다 한 가지가 꼬였습니다. 결과가 같은 것이 맞습니다^^;)
프로모션별 매출액(payment)은 프로모션 유형별 매출의 양상을 계산할 때에만 쓰입니다.
이 양상은 프로모션 매출액의 규모와 관계없이 0~1사이의 값을 갖도록 scaling되고, 이 값을 토대로 전체 매출에 프로모션이 미친 효과를 산출하기 때문에 전체 매출이 동일하고, 유형에 관계 없이 시간에 따른 매출의 양상이 일직선으로 동일한 예제에서는 효과가 동일하게 계산되는 것입니다.
다시 말해, payment에서는 매출의 규모가 아니라 프로모션 진행에 따른 모양만 본떠오는 형식이기 때문에 적어주신 예제에서 효과 값이 동일한 것입니다. 따라서 payment가 아니라 sim.data의 simulated_sales 즉, 전체 매출을 다르게 설정하시면 값이 달라지는 것을 관찰하실 수 있습니다.

감사합니다.

**Comment by akclau** [comment]
아 같은게 정상이군요~ 
자세한 설명 감사드립니다.!
