### ISSUE TITLE
invalid 'times' argument

### ISSUE THREAD

**Issue by loveulee** [ncsoft/promotionImpact#6]
안녕하세요. 좋은 패키지 공유 감사합니다.
다름이 아니라, 사용 중 데이터셋을 제가 가진 것으로 사용했더니 에러가 발생하는 부분이 있어 이슈 남깁니다.
에러 메시지는 하단과 같습니다.
Error in rep(seq(nrow(promotion)), promotion[, "duration"]) : 
  invalid 'times' argument

#----------------------------#
제가 분석에 사용한 코드는 
pri1 <- promotionImpact(data = sim.data, promotion = ex3, 
                        time.field = "V1" ,
                        target.field = "Tot_Sum_Q", 
                        dummy.field = "Day_Week",
                        trend = T, 
                        #period = 30.5, 
                        #trend.param = 0.02, 
                        #period.param = 2, 
                        logged = TRUE, 
                        differencing =TRUE, 
                        synergy.promotion = FALSE, 
                        synergy.var = NULL, allow.missing = TRUE)

입니다. sim.data, promotion모두 제 데이터를 사용했습니다.
해당 에러는 어떤 상황에서 발생하는것인지 알수있을까요?
참고로, promotion데이터의 칼럼명이나 형식등은 샘플 데이터셋과 동일하게 가공한 후 코드를 돌렸습니다.

**Comment by danbi-ncsoft** [comment]
확인이 늦었습니다. 
해당 에러는 질문자분의 ex3데이터의 start_dt와 end_dt로부터 프로모션의 기간을 계산하는 과정에서 발생한 에러로 보입니다.
대표적으로 시작일보다 종료일이 더 이른 경우에 동일한 에러가 발생할 수 있으며, 
시작일과 종료일을 중심으로 데이터 자체에 잘못된 내용이 없는지 다시 한번 확인해 보시기 바랍니다.
말씀드린 경우가 아니라면 사용하신 데이터의 예시를 좀 더 구체적으로 알려주시면 추가적으로 확인이 가능할 것 같습니다.
감사합니다.
